# ──────────────────────────────────────────────────────────
#  Render Infrastructure-as-Code
# ──────────────────────────────────────────────────────────
services:
  - name: sstm-api
    type: web
    env: docker
    plan: free
    autoDeploy: true

    envVars:
      # A string de conexão será injetada automaticamente
      - key: DATABASE_URL
        fromDatabase:
          name: sstm-db
          property: connectionString

    # 👉 As variáveis sensíveis (JWT_SECRET, ADMIN_EMAIL, ADMIN_PWD_HASH…)
    #    serão criadas manualmente no dashboard do Render.
    healthCheckPath: /docs

databases:
  - name: sstm-db
    databaseName: sstm
    user: sstm_user
    plan: free
    ipAllowList: []
